RANDOM_SEED = 0
T_YEAR = 360.0
T_BURNIN = 100.0 * T_YEAR
T_END = 200.0 * T_YEAR

SAMPLE_DB_FILENAME = 'sample_db.sqlite'

CHECKPOINT_SAVE_FILENAME = 'checkpoint_db.sqlite'
CHECKPOINT_SAVE_PERIOD = T_YEAR * 20
LOAD_FROM_CHECKPOINT = False
CHECKPOINT_LOAD_FILENAME = ''

OUTPUT_HOSTS = True
OUTPUT_GENES = True
OUTPUT_STRAINS = True

HOST_SAMPLING_PERIOD = 30.0
TRANSMISSION_EVENT_SAMPLING_SKIP = 1000

N_GENES = 50
N_GENES_PER_STRAIN = 5

P_MUTATION = 0.01
P_STRAIN_RECOMBINATION = 0.05

T_LIVER_STAGE = 7.0

HOST_LIFETIME_PDF = [0.3] * 20 + [0.4] * 10

N_POPULATIONS = 1

N_HOSTS = [10000]
N_INITIAL_INFECTIONS = [100]

BITING_RATE_MEAN = [1.4]
BITING_RATE_RELATIVE_AMPLITUDE = [0.05]
BITING_RATE_PEAK_PHASE = [0.0]

IMMIGRATION_RATE = [0.1]

CLEARANCE_RATE_CONSTANT_IMMUNE = 1.0
CLEARANCE_RATE_CONSTANT_NOTIMMUNE = 1.0
CLEARANCE_RATE_POWER = 0.0

BASELINE_ACTIVATION_TIME = 1.0

MAX_EXPRESSION_TIME = 1.0
MAX_TRANSMISSIBILITY = 1.0
ANTIGENIC_PROFILE = [[1]]

TRANSMISSIBILITY = [0.8]
EXPRESSION_TIME = [4.0]
ACTIVATION_POWER = [0.0]
TRANSMISSIBILITY_POWER = [-1.0]
IMMUNITY_LOSS_RATE = [0.1]

MUTATION_WEIGHTS = [[1.0]]
