from shared_test_params import *

RANDOM_SEED = 1

N_GENES_INITIAL = 1200
N_GENES_PER_STRAIN = 60
N_LOCI = 2
N_ALLELES_INITIAL = N_LOCI * [120]

SELECTION_MODE = 'SPECIFIC_IMMUNITY'
N_INFECTIONS_FOR_GENERAL_IMMUNITY = 0
GENERAL_IMMUNITY_PARAMS = [-1, -1, -1, -1]

TRANSITION_RATE_NOT_IMMUNE = 2.0 / 3.0
CLEARANCE_RATE_IMMUNE = 0.0001

BITING_RATE_MEAN = [0.2]
